language: java
install: true

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-8
    - g++-8

stages:
- name: build
- name: snapshot
  if: branch = development
- name: release
  if: branch = master

jobs:
  include:
  - stage: build
    script: ./gradlew build
  - stage: snapshot
    script: ./gradlew artifactoryPublish --exclude-task test -Dbintray.user=${BINTRAY_USER} -Dbintray.key=${BINTRAY_KEY} -Dbuild.number=${TRAVIS_BUILD_NUMBER}
  - stage: release
    script: ./gradlew bintrayUpload --exclude-task test -Drelease=true -PbuildVariant=release Dbintray.user=${BINTRAY_USER} -Dbintray.key=${BINTRAY_KEY} -Dbuild.number=${TRAVIS_BUILD_NUMBER}

deploy:
  provider: releases
  api_key: ${ACCESS_TOKEN}
  skip_cleanup: true
  file: build/libs/dxutils-${TRAVIS_TAG}.jar
  on:
    repo: hhu-bsinfo/dxutils
    branch: master
    tags: true
